# Generated by Django 3.0.5 on 2020-08-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
