# Generated by Django 3.0.5 on 2020-08-25 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_review_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
