# Generated by Django 3.0.5 on 2020-08-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('image', models.FileField(upload_to='client_images')),
                ('review_text', models.TextField()),
            ],
        ),
    ]
